### ISSUE TITLE
Feature Request: choose video quality

### ISSUE THREAD

**Issue by davelamorte** [bekriebel/fvtt-module-avclient-livekit#15]
Hello bekriebel!

Thank you so much for you hard work on this new module.

It wasn't easy but I have now setup a working livekit server on a local VM.
What I noticed right away, is that the video quality is far too excessive for VTT use. Each webcam is set at 720p, but on Foundry's window you have the videos pretty small, more like 100-240p.
Since this is data consuming, but also high CPU/GPU demanding, especially for laptops, could you add a setting where the GM can choose the max video quality for the room? Having the setting would be the best though, if it's easier for you, even simply reducing the quality to 240p would make sense for almost everybody I think.

Thank you again!

**Comment by davelamorte** [comment]
I see they have this in the SDK:

```
 export const VideoPresets = {
  h216: new VideoPreset(384, 216, 180_000, 15),
  h360: new VideoPreset(640, 360, 300_000, 20),
  h540: new VideoPreset(960, 540, 600_000, 25),
  h720: new VideoPreset(1280, 720, 1_700_000, 30),
  h1080: new VideoPreset(1920, 1080, 3_000_000, 30),
  h1440: new VideoPreset(2560, 1440, 5_000_000, 30),
  h2160: new VideoPreset(3840, 2160, 8_000_000, 30),
} as const;
```

Being able to choose between those would be great. Or even just "low-mid-high".

**Comment by bekriebel** [comment]
This is already done automatically with the use of simulcast and dynacast. It will automatically select the resolution needed to support the window size that any viewers are using. It will briefly start at 720p, but very quickly scale down (even to nothing if no other users are on).

This has two added benefits. First, when a larger number of users are on and the video windows get smaller to fit them all on screen, the resolution drops even further to scale to the tiny images. Second, if a particular user is popped out into a larger window, it can scale up to 720p and still look good.

I closely monitor bandwidth usage on my patreon cluster. Since switching to this method, bandwidth usage is down significantly compared to when I had it fixed at 320p (the size of the larger AV window). Also, users have reported that the overall performance is drastically improved since it also scales down when needed due to end user bandwidth or other resource limitations.

**Comment by davelamorte** [comment]
Thank you for replying!
I will do some more testing and report back if needed.
My initial test, with only 2 people on, small floating windows (about 100px), my server was outputting 1.2mbit, quite a bit. And the user on a mac laptop immediately had the fan started (which usually never does even playing for hours on easyrtc/jitsi), my rtx2070 was at 24% (of idle mode). I suspect simulcast and dynacast are either not working on my server, or something else is happening. Maybe the floating windows don't let the video scale down even when small?

**Comment by bekriebel** [comment]
The floating window should still let it scale.

I didn't think this was a required option, but you may want to turn on adaptive streaming in your server config. I turn that on but turn off the adaptive pausing on my servers.

**Comment by bekriebel** [comment]
Oh, and make sure you are using a newer server version. 0.15.7 is recommended right now.
