### ISSUE TITLE
Audio settings for the Foundry Client

### ISSUE THREAD

**Issue by omnibelt** [bekriebel/fvtt-module-avclient-livekit#26]
Hey there, this is Brian Mc from the Livekit Slackchat. As requested I'm writing a ticket to remind you about my request for a setting for the publishing rates for audio be added to the module.

Appreciate you reaching out in Slack chat and adding this in! (To be specific I was hoping for somewhere about 128kbps to 256kbps, I think right now the default is 20kbps.)

**Comment by bekriebel** [comment]
It turns out that it isn't just the bitrate that is affecting the audio quality, but also settings like noise suppression and echo cancelation.

How I'm going to implement this is to add an option for "Music Streaming Mode" that will increase the bitrate and disable all of the other audio features like noise suppression. Since these features are normally desired for voice chatting, you wouldn't want to use it for normal voice communication unless your microphone setup is very good. However, you'll be able to set this for any user account that you are publishing music audio tracks from.

**Comment by omnibelt** [comment]
This should work perfectly for what I was looking for!
