### ISSUE TITLE
Instructions in wiki is flawed due to multiple uses of port 443

### ISSUE THREAD

**Issue by DAMO238** [bekriebel/fvtt-module-avclient-livekit#34]
Given that the assumption that Foundry is installed behind NginX, with TLS, then it stands to reason that port 443 will already be in use by NginX. Therefore, when the livekit-docker.service, which is installed via the instructions given, requires the use of port 443, this fails, and thus docker will continuously restart, trying to start up livekit and thus all requests by Foundry will result in 502 (Bad Gateway). If it is of any relevance, I also needed to add the following line to both NginX configs to enable IPv6 to get TLS certificates: `listen [::]:80;`. If anyone has any solutions, it would be greatly appreciated.

**Comment by bekriebel** [comment]
I had someone report this recently in our discord. I'm not sure if something changed since the guide was written or if a step wasn't included. I believe the way the user got around it was commending out the caddy section of the livekit docker compose file.

I haven't run through this guide myself. I'll try to take some time to run though this sometime soon, but if someone else would like to take on and update the wiki, I'd appreciate it.

**Comment by DAMO238** [comment]
That worked, I will work on a pull request with those changes! Thank you!
