### ISSUE TITLE
Integration with OBS or other broadcasting software

### ISSUE THREAD

**Issue by FreshnessDND** [bekriebel/fvtt-module-avclient-livekit#39]
I am curious what integration this would have with OBS and like software.

I'd inquire directly, but I can only do so after subscribing to your Patreon and I am not sure if this has the capabilities I need.

Is there a way to route a feed of each video & audio?

Thanks!

You can reach back to me directly Freshness#1448 on Discord or email via freshnessdnd@gmail.com if you prefer.

**Comment by bekriebel** [comment]
There is currently no direct integration with OBS. If you are running you own server, it might be possible to LiveKit's Egress option: https://github.com/livekit/egress - but that is not currently available on my server cluster.

We may provide something like this in the future, but it would likely have to be at a higher price due to the costs associated with running a service like that.

You're also welcome to join out discord (https://tavern.at/discord) - There are private channels for Patreon subscribers, but there are public channels available for discussion of the module itself.
