### ISSUE TITLE
How do you change SSL certificate?

### ISSUE THREAD

**Issue by AsterITA** [bekriebel/fvtt-module-avclient-livekit#4]
Hi, I read the guide on how to deploy a livekit server on a VM providing an SSL certificate but how can I change it with a new one when said certificate expires?

Is there a way to use the certbot auto-renewal feature?

Thanks in advance for the help!

**Comment by bekriebel** [comment]
To be honest, I'm not sure what the best practice would be for that. The best bet would probably be to sign into the VM and install set up certbot auto-renew with the nginx plugin as usual. The VM guide just uses the init scripts to set up nginx with a default config. That config could be changed to point to the nginx certificate with normal auto-renew schedules enabled.

Hope this helps! I'm going to go ahead and close the issue since it's not directly related to the module, but I'm happy to discuss more in the comments if this isn't enough info.
