### ISSUE TITLE
[Feature] Quality setting?

### ISSUE THREAD

**Issue by lozanoje** [bekriebel/fvtt-module-avclient-livekit#43]
According to the Livekit docs there is an option for that:

!https://docs.livekit.io/server/room-management/#videoquality

But not sure if (sending) video quality is a setting a client can change.

If so, it would be great to have a setting to change video quality to control bandwidth.

**Comment by bekriebel** [comment]
The current version automatically scales the video quality used based on the size of the video windows. So, for instance, when the windows are in their smaller docked mode, it is essentially already streaming at a "low" quality because the resolution is quite small. If you pop out a video window and expand it to a larger size, you should see the quality improve within a few seconds (as long as bandwidth allows).

On top of this, it uses LiveKit's logic to further scale up/down video quality based on the connection quality and bandwidth.

Since quality already automatically adjusts, and is already at a pretty low setting when using the standard dock, I have no plans to introduce an additional setting to modify this.
