### ISSUE TITLE
Add screen share functionality

### ISSUE THREAD

**Issue by kristianserrano** [bekriebel/fvtt-module-avclient-livekit#48]
I think I read somewhere the screensharing is possible in LiveKit. I was curious if that could be added as a feature in the module.

**Comment by bekriebel** [comment]
This is actually already available, however it is a hidden feature because I don't have the time to commit to ensuring it is fully functional and supported. I use it for my own personal testing of the module, though.

You can start a screen share with your developer console or with a script macro by running `await game.webrtc.client._liveKitClient.shareScreen(true);` and stop a screen share with `await game.webrtc.client._liveKitClient.shareScreen(false);`

![image](https://user-images.githubusercontent.com/183779/228663954-07a36271-d4a7-4659-ad49-9d717307c144.png)

**Comment by kristianserrano** [comment]
That works well enough, thanks!

**Comment by kristianserrano** [comment]
Just in case anyone else comes looking for this, here's the macro I wrote to toggle it off and on.
```js
// Get liveKitClient.
const liveKitClient = game.webrtc.client._liveKitClient;
// Determine whether there is currently an active screenTrack and set the boolean to the opposite.
const toggleBoolean = !(liveKitClient.screenTracks.length > 0 && liveKitClient.screenTracks[0].isSimulcast);
// Toggle the shareScreen state.
await liveKitClient.shareScreen(toggleBoolean);
```

**Comment by mikenerone** [comment]
I've made a macro that works slightly differently. The toggle approach has a small UX problem for me, because I'm used to clicking the browser's "Stop Sharing" button to stop the screen sharing. That button works, but LiveKit isn't notified about it, so the user's camera isn't reactivated. Instead of a toggle, the macro below is only for starting the screen share, and you just click the browser's "Stop Sharing" button to stop it.  The macro attaches a handler to the screen stream so that when it's ended, LiveKit's automatically called so it can restore what you had before.

```javascript
const liveKitClient = game.webrtc.client._liveKitClient;

await liveKitClient.shareScreen(false);  // In case screen share was active
await liveKitClient.shareScreen(true);  // Note: If user declines, execution stops
console.log("Started LiveKit screen sharing");

liveKitClient.screenTracks[0].mediaStreamTrack.onended = async () => {
  console.log("Notifying LiveKit: screen sharing ended");
  await liveKitClient.shareScreen(false);
};
```

**Comment by kristianserrano** [comment]
Nicely done! Thank you!
