### ISSUE TITLE
[QUESTION] AVKit audio quality for loopback audio stream "user"

### ISSUE THREAD

**Issue by Juppstein** [bekriebel/fvtt-module-avclient-livekit#65]
As per the wiki entry for enabling the loopback device with pipewire I would like to stream an external audio source into the AVKit server (self hosted on an Ubuntu box). 

The problem I have at the moment is that the audio quality seem to get downsampled quite a bit. I would even say it gets beaten into a mono track. Is ther a way to set a certain audio quality ? 

I have enough bandwidth for that if it would affect all participants, but it would be super nice if I could define hi-fi quality only for the audio streaming dummy user.

**Comment by bekriebel** [comment]
Have you tried enabling Music Mode in the module settings on the account you are streaming from? Streaming audio doesn't sound good with default voice mode audio because of things like echo cancelation and noise impression. Enabling that mode turns off those features and also gives you an adjustable bitrate option.

**Comment by Juppstein** [comment]
Yup, that was it. I read about the music mode but thought it was something to configure on the server side. Thanks, streamed audio sounds much better now.
