### ISSUE TITLE
Connection Time out

### ISSUE THREAD

**Issue by jsavko** [bekriebel/fvtt-module-avclient-livekit#7]
Hello,  I've setup the livekit server using your fly.io directions found here: https://github.com/bekriebel/livekit-flydotio

I can see the connection established and the room created in the fly.io logs 
![image](https://user-images.githubusercontent.com/192591/153324352-3ac19215-7dc8-4443-8e54-2a87e954ca2d.png)

However foundry reports 
![image](https://user-images.githubusercontent.com/192591/153324532-4dfefed4-3ab4-4fad-a28b-497734921524.png)
![image](https://user-images.githubusercontent.com/192591/153324633-2c457079-625c-4d95-ad99-f77dd6fd58fb.png)

I've redeployed the image a couple times and generated new API keys. Not sure why it's failing to connect. Any ideas?

**Comment by jsavko** [comment]
Interestingly enough with this module enabled the camera only returns a black screen but when disabled and using foundry's built in video the camera views correctly.  Not sure if it's related but thought it might be helpful

**Comment by bekriebel** [comment]
I started having issues with my Fly.io instances recently as well. Unfortunately, I haven't had time to diagnose the problem and instead of switched hosting of my cluster to a different provide. At this time, I can't continue to recommend using Fly for hosting LiveKit. I'll remove it as a recommended option from the documentation.
